# syntax=docker/dockerfile:1

ARG NODE_VERSION=20

FROM node:${NODE_VERSION}-alpine

ENV NODE_ENV production

ARG FARMING_SIMULATOR_BOT_DB_PATH
ARG FARMING_SIMULATOR_BOT_DISABLE_CERTIFICATE_VERIFICATION
ARG FARMING_SIMULATOR_BOT_DISABLE_SAVEGAME_MESSAGES
ARG FARMING_SIMULATOR_BOT_DISABLE_UNREACHABLE_FOUND_MESSAGES
ARG FARMING_SIMULATOR_BOT_DISCORD_CHANNEL_NAME
ARG FARMING_SIMULATOR_BOT_DISCORD_SERVER_NAME
ARG FARMING_SIMULATOR_BOT_DISCORD_TOKEN
ARG FARMING_SIMULATOR_BOT_FETCH_RETRIES
ARG FARMING_SIMULATOR_BOT_FETCH_RETRY_DELAY_MS
ARG FARMING_SIMULATOR_BOT_POLL_INTERVAL_MINUTES
ARG FARMING_SIMULATOR_BOT_PURGE_DISCORD_CHANNEL_AFTER_DAYS
ARG FARMING_SIMULATOR_BOT_PURGE_DISCORD_CHANNEL_AFTER_LINES
ARG FARMING_SIMULATOR_BOT_PURGE_DISCORD_CHANNEL_HOUR
ARG FARMING_SIMULATOR_BOT_PURGE_DISCORD_CHANNEL_NAME
ARG FARMING_SIMULATOR_BOT_PURGE_DISCORD_CHANNEL_ON_STARTUP
ARG FARMING_SIMULATOR_BOT_PURGE_DISCORD_CHANNEL_SERVER_NAME
ARG FARMING_SIMULATOR_BOT_URL_CAREER_SAVEGAME
ARG FARMING_SIMULATOR_BOT_URL_SERVER_STATS

WORKDIR /usr/src/app

RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci --omit=dev

USER node

COPY . .

CMD [ "node", "./bin/server.js" ]
